Add Medium Speed Contest rules
Tlf/tlf pull request #393
Opened 2023-06-12 21:40 UTC by VictorDenisov

2023-06-13 19:06 UTC, zcsahok commented
I believe it works even with plain TLF configs. At least with these ones it passed the test:

```
ONE_POINT
UNIQUE_CALL_MULTI=BAND
```

2023-06-15 21:08 UTC, zcsahok requested changes
Just added some comments.

2023-06-15 21:08 UTC, zcsahok commented on rules/mst/mst
> +#SERIAL_OR_SECTION
Unused lines could be dropped. (the ones commented out + PLUGIN_CONFIG)

2023-06-15 21:08 UTC, zcsahok commented on rules/mst/mst
> +CABRILLO-EXCHANGE=vic ca
Not sure if this is relevant/correct. No Cabrillo has to be submitted.

2023-06-15 21:08 UTC, zcsahok commented on test/rules/mst/rules/mst.py
> +../../../../rules/mst/mst.py
pls remove the symlink to `mst.py`

2023-06-18 05:12 UTC, VictorDenisov commented
Done

2023-06-18 18:18 UTC, zcsahok approved these changes

2023-06-18 18:19 UTC, merged